name: CI

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pip-tools
        run: pip install --no-cache-dir pip-tools

      - name: Compile requirements
        run: pip-compile requirements.in --output-file requirements.txt

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Build Docker image
        run: docker build -t smartbooks:${{ github.sha }} .

      - name: Run black
        run: docker run --rm smartbooks:${{ github.sha }} black --check .

      - name: Run pylint
        run: docker run --rm smartbooks:${{ github.sha }} pylint app.py tests

      - name: Run pytest
        run: docker run --rm smartbooks:${{ github.sha }} pytest
